apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: My_dep
spec: 
   selector: 
     matchLabels: 
      app: My_dep 
replicas: 2
  template:
    metadata: 
      labels: 
        app: My_dep
    spec: 
      containers: 
      - name: My_dep
        image: fdehech/my_project:main
        ports: 
        - containerPort: 80 
