apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: projet-deployment
spec: 
  selector: 
    matchLabels: 
      app: projet
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: projet
    spec: 
      containers: 
      - name: projet
        image: fdehech/my_project:main
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
# kind: Service 
# apiVersion: v1 
# metadata: 
#  name: projet-service
# spec: 
#  selector: 
#    app: projet
#  ports: 
#  - protocol: TCP 
#    port: 80 
#    targetPort: 80 
#  type: LoadBalancer 
